### ISSUE TITLE
Extract certain individuals from a vcf

### ISSUE THREAD

**Issue by Duhyadi** [Duhyadi/Deleterious-alleles-in-landraces-of-maize#2]
I would like to extract certain individuals from a vcf file. I would like to do another type of analysis with the data coming from the SNP array. Only for Olotillo. I think the following script may work. However, it can't run.

`library(vcfR)
vcf <- read.vcfR(vcf_file, verbose = FALSE )
gt <- extract.gt(vcf, element = c('GT'), as.numeric = TRUE)
`

In Tassel it was easy, but I would like to try it in R.

# Help, please

**Comment by tono2204** [comment]
Hello Duhya, 
 I think that the information contained in this link can be really helpful https://stackoverflow.com/questions/21598212/extract-sample-data-from-vcf-files.

:)

**Comment by tono2204** [comment]
Since VariantAnnotacion is a Bioconductor package, you have to install it with the following code:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("VariantAnnotation")

```

**Comment by tono2204** [comment]
In vcftools, you can use the following flag (http://vcftools.sourceforge.net/man_latest.html#INDIVIDUAL%20FILTERING%20OPTIONS):

INDIVIDUAL FILTERING OPTIONS
These options are used to include or exclude certain individuals from any analysis being performed by the program.

--indv <string>

**Comment by Duhyadi** [comment]
# Hi,

With the following script (in R) I was able to extract certain individuals from the vcf file. Specifically, individuals 12 (race celaya) and 41 (elotes occidentales).

## Load library
`library(data.table)`

## Vcf
## to access the data folder from the bin folder
`file = "../Data/new_final_26_march.vcf"`

## Extract columns for a specific race
`select_colum<- fread(file, select = c("5_maiz_12","6_maiz_41"))`
