### ISSUE TITLE
Preliminary evaluation

### ISSUE THREAD

**Issue by Rodolfo47** [Duhyadi/Deleterious-alleles-in-landraces-of-maize#5]
Hi Duhyadi,
Although I think you repo are a bit complex, are well structured. In your generar READMY.md you must have a link to each paper.
why there are not an Arteaga/README.mb but inside of the preliminar/ dir do? I thing that all this scripts anda results are indeed preliminar results
Good work!

**Comment by Duhyadi** [comment]
Thanks for the suggestions, I added the link of each of the posts.

**Comment by Rodolfo47** [comment]
Hi Duhya,
I see you have include in the general README.md the links to the papers you are using in your repo
And you update the internal structure of /Arteaga_SNPArray_2016/ and /Rojas_GBS_2019/
Well done!!
